name: Integration Tests
on: [pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd enhanced-node-network
          pip install -r requirements.txt
      - name: Run integration tests
        run: |
          cd enhanced-node-network
          pytest tests/integration
